config/routes.rb
Rails.application.routes.draw do

  namespace :admin do 
    resources :users do
      member do
        put :switch
      end
    end
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create]

  resource :session, only:[:new, :create, :destroy]

  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  mount_uploader :image, ImageUploader

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :image,
    presence: true

  validates :release_date,
    presence: true

  # validate :release_date_is_in_the_future

  def review_average
    if reviews.size < 1 
      return "Not Yet Rated" 
    else
      reviews.sum(:rating_out_of_ten)/reviews.size
    end
  end

  def self.search(search)
    if search
      self.where('title LIKE ? OR director LIKE ? OR description LIKE ?', ["%#{search[:search]}%"], ["%#{search[:search]}%"], ["%#{search[:search]}%"]).runtime(search[:runtime])
    else
      find(:all)
    end
  
  end

  def self.runtime(runtime)
    case runtime
      when '1'
        self.where('runtime_in_minutes > 0')
      when '2'
        self.where('runtime_in_minutes <= ?', 90)
      when '3'
        self.where('runtime_in_minutes > ? AND runtime_in_minutes < ?', 90, 120)
      when '4'
        self.where('runtime_in_minutes >= ?', 120)
      else
        self.all
      end
  end


  protected

  # def release_date_is_in_the_future
  #   if release_date.present?
  #     errors.add(:release_date, "should probably be in the future") if release_date < Date.today
  #   end
  # end
  
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  
  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "Successfully created, #{@user.firstname}!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.fuckyou_email(@user).deliver
    @user.destroy
    redirect_to admin_users_path
  end

  def switch
    @user = User.where(admin: [false, nil]).find(params[:id])
    session[:admin_id] = current_user.id
    session[:user_id] = @user.id
    redirect_to movies_path, notice: "Switched"
    @@preview = true
  end

  def switch_back

    @@preview = false
  end

  protected

   def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin?
    if current_user
      @user = User.find(session[:user_id])
      @user.admin
    else
      return false
    end
  end

  def mimicing?
    actual_user.present?  
  end

  def actual_user
    @actual_user ||= User.where(admin: true).find_by(id: session[:admin_id]) if session[:admin_id]
  end


  helper_method :admin?
  helper_method :current_user
  helper_method :mimicing?
  helper_method :actual_user
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.search(params)
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end


  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(:title, :director, :runtime_in_minutes, :description, :poster_image_url, :release_date, :image, :remote_image_url)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
      @true_session = user.id
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    if mimicing?
        session[:user_id] = session[:admin_id]
        session[:admin_id] = nil
        redirect_to :back, notice: "Admin again!"
    else
      session[:user_id] = nil
      redirect_to movies_path, notice: "Adios!"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ERDERTING URSER!</h1>

<%= link_to 'Back to Users', admin_users_path %>

<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div>
    <%= f.label "Make Admin" %><br>
    <%= f.check_box "admin" %>
  </div>

  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/index.html.erb
<h1>Admin User Index</h1>
<%= link_to 'Back to Movies', movies_path %> |
<%= link_to "Create New User", new_admin_user_path %>
<hr>

<% @users.each do |user| %>
<%= link_to user.full_name, admin_user_path(user) %>
<hr>
<%end%>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= link_to 'Back to Users', admin_users_path %>


<%= form_for [:admin, @user] do |f| %>
 <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div>
    <%= f.label "Make Admin" %><br>
    <%= f.check_box "admin" %>
  </div>

  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
<%= link_to 'Back to Users', admin_users_path %>

<h2><%= @user.full_name %> 
  <small><%= link_to 'Switch view to this user', switch_admin_user_path(@user), method: :put %></small>
</h2>
  
<h3>email address: <%= @user.email %></h3>
<h3>First Created: <%= @user.created_at %></h3>
<h3>Last Updated: <%= @user.updated_at %></h3>
<h3>Is Admin? <%= @user.admin %></h3>

<hr>

<h3>
  <%= link_to "Edit",  edit_admin_user_path(@user) %>
  |
  <%= link_to "Delete", admin_user_path(@user), method: :delete, confirm: "You sure?" %>
</h3>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
          
      <% if mimicing? %>
        |Actually logged in as <%= actual_user.full_name %>. <%= link_to "Switch back", session_path("current"), method: :delete %>. |
      <% end %>

  </small>


  <small>
    <% if admin? %>
      <%= link_to "Admin Tools", admin_users_path %>
    <% end %>
  </small>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |f| %>
  
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "Title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "Director" %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "Runtime (In Minutes)" %><br>
    <%= f.text_area "runtime_in_minutes" %>
  </div>
    <div>
    <%= f.label "Description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.label "Upload Poster Image" %><br>
    <%= f.file_field "image" %>
  </div>
  <div>
    <%= f.label "Or link to Image" %><br>
    <%= f.text_field "remote_image_url" %>
  </div>

    <div>
    <%= f.label "Release Date (YYYY-MM-DD)" %><br>
    <%= f.text_area "release_date" %>
  </div>
  <div>
    <%= f.submit "Save" %> 
  </div>

<% end %>

app/views/movies/edit.html.erb
<h1>ERDERTING MERVERS!</h1>
<%= link_to 'Back to Movies', movies_path %>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Movies!</h1>

<h2><%= link_to "Add a Movie!", new_movie_path %></h2>

<hr>

<h4>Search for a movie by Title, Director or Keyword</h4>
<%= form_tag movies_path, method: "get" do %>
  <div>
    <%= text_field_tag :search, params[:search] %>
    
    <%= select_tag(:runtime, options_for_select([['Any Length', 1], ['Under 90 Minutes', 2], ['Between 90 and 120 Minutes', 3], ['More than 2 Hours', 4]], params[:runtime])) %>

    <%= submit_tag "Search", name: nil %> 
  </div>
<% end %>

<hr>

<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.image_url(:thumb)), movie_path(movie) %>
  <hr>
<% end %>

app/views/movies/new.html.erb
<h1>New Movie!</h1>
<%= link_to 'Back to Movies', movies_path %>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to 'Back to Movies', movies_path %>

<h2><%= @movie.title %><small> Directed by <%= @movie.director %></small></h2>

<%= image_tag(@movie.image_url(:thumb)) %>

<h3>Runtime: <%= @movie.runtime_in_minutes %> minutes</h3>
<h3>Release Date: <%= formatted_date(@movie.release_date) %></h3>


<h3>Average Review Score: <em><%= @movie.review_average %></em></h3>

<p><%= @movie.description %></p>

<hr>
<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
<% @movie.reviews.each do |review| %>
  <p><%= review.text %></p>
  <p><%= review.rating_out_of_ten %>/10</p>
  <small>- <%= review.user.full_name %></small><br/>
<% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>
<hr>

<h3>
  <%= link_to "Edit", edit_movie_path(@movie) %>
  /
  <%= link_to "Delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>
</h3>

app/views/notifications/deleted.html.erb
Hey guy, we deleted your account. Fuck you!

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>